import { Customer, Footer, Navbar } from "../../component/Component";

export function Terms() {
  return (
    <div className="container-fluid main">
      <Navbar />
      <Customer
        className={"col-md-12 terms text-center"}
        h1={"Terms and Conditions"}
        p={"Home > Terms and Conditions"}
      />
      <div className="col-lg-10 terms-page mx-auto my-3">
        <h3 className="text-center  py-3">TERMS AND CONDITIONS</h3>
        <p>This user terms and conditions is an electronic record in the form of an electronic contract under the Information Technology Act, 2000 and the rules made thereunder and the amended provisions pertaining to electronic documents/ records in various statutes as amended by the Information Technology Act, 2000 from time to time. This document is published in accordance with the provisions of rule 3(1) of the Information Technology (Intermediaries guidelines) rules, 2011 that require publishing the rules and regulations, privacy policy and terms of use for access to or usage of www.Paypepl.com (hereinafter referred to as “Website”. This privacy does not require any physical, electronic or digital signature.</p>
        <p>The Website www.Paypepl.com is owned and operated by Paype Limited (hereinafter referred to as “Paype”), a company incorporated under the Companies Act, 2013, with its registered office at 102, Ganga Chamber, 64/1, W.E.A. Karol Bagh, New Delhi- 110005.</p>
        <p>For the purpose of these ToU, wherever the context so requires “You/you”, Your/your”, “User/user” or “Merchant” shall mean any non-registered individual or corporate body, registered user of Paype including but not limited to Paype merchants. The term “Paype”, “We/we”, “Us/us” and “Our/our” shall mean the Paype Limited.</p>
        <h5 className="py-3">I. ACCEPTANCE OF TERMS</h5>
        <ol>
            <li>Your use of the Website is governed by the following Terms of Use (“ToU”) as applicable to Paype including the applicable policies which are incorporated herein by way of reference. Please read to these carefully. By accessing or using the Website, you are agreeing to these ToU and concluding a legally binding contract with the Company. You may not use the Services if you do not accept the ToU or are unable to be bound by it.</li>
            <li>When you use any of the services (“Services”) provided by us through the Website, you will be subject to the rules, guidelines, policies, terms and conditions applicable to such Service, and they shall be deemed to be incorporated into this ToU and shall be considered as part and parcel of this ToU.</li>
            <li>We reserve the right, at our sole discretion, to change, modify, add or remove portions of these ToU, at any time without any prior notice to you. You are advised to regularly check for any amendments or updates to the ToU from time to time. As long as you comply with these ToU, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.</li>
            <li>In order to use the Website, you must agree to the ToU. You can accept the ToU by clicking to accept or agree to the ToU, where it is made available to You by Company in the user interface or actually using the Services.</li>
        </ol>
        <h5 className="py-3">II. ELIGIBILITY TO USE THE WEBSITE</h5>
        <ol>
            <li>You hereby represent and warrant that you (a) have full capacity and authority to agree and bind yourself to these ToU; (b) are eighteen years of age or older; (c) are an Indian resident; and (d) have all requisite licenses, registrations, rights, power, and authority in full force to enter into these ToU. If you represent an entity, organisation, or any other legal person, you confirm and represent that you have the necessary power and authority to bind such entity, organisation or legal person to these ToU.</li>
            <li>You are in compliance with all laws and regulations of India when you access and use the Website. Company reserves the right to deny access to use the Services offered at the Website to new Users or to terminate access granted to existing Users at any time without furnishing any reasons for doing so.</li>
        </ol>
        <h5 className="py-3">III. WEBSITE USER ACCOUNT</h5>
        <ol>
            <li>You must create an account in order to use the Services offered by the Website by setting up a username and password which will be linked to your phone number and email address (“Account”). Use of any personal information you provide to us during the account creation process is governed by our Privacy Policy. You shall be responsible for maintaining the confidentiality of your Account. You agree that if you provide any information that is untrue, inaccurate, not current or incomplete, we shall have the right to indefinitely suspend or terminate or block access of your membership on the Website.</li>
            <li>You may also be able to register to use the Website by logging into your account with your credentials from certain third-party social networking sites. You confirm that you are the owner of any such social media account and that you are entitled to disclose your social media login information to us. You authorize us to collect your authentication information, and other information that may be available on or through your social media account consistent with your applicable settings and instructions.</li>
            <li>You are responsible for all the activities that occur in your account. You agree to notify us immediately of any unauthorized use of your Account in order to enable us to take necessary corrective action. You must ensure that you log out from your Account at the end of each session to prevent misuse of your Account.</li>
            <li>You agree to receive communications from us regarding (a) information relating to transactions on the Website by your Account; (b) transaction amount received; (c) information about us and the Services; (d) promotional offers and services from us and our third-party partners; and (e) any other matter in relation to the Services.</li>
        </ol>
        <h5 className="py-3">IV. SCOPE OF SERVICES</h5>
        <ol>
            <li>We are engaged in the business of offering e-commerce services which will include payments and accepting instructions through the internet in respect of payments to be made by the customers (“Customers”) using valid payment instruments to purchase/avail products and services and accordingly transfer funds from the Customer’s bank account to the merchant’s bank account.</li>
            <li>We are signed up with facility providers and has requested them to accept the instructions given by Customers of merchants through a valid online payment instrument and support us to facilitate the online transactions. In the event of any unsuccessful payments, the money so debited shall be credited back to the source account in accordance with the facility provider’s term.</li>
            <li>You hereby agree that all transaction amounts collected shall be settled with you in accordance with the facility provider terms. Paype shall charge a commission on each transaction. Such commission is deductible from the payment received from the Customer. Such commission may be changed by us at our sole discretion. We shall undertake best efforts to inform you of the revised commission by indicating the same on our Website, however, you shall solely be responsible for visiting the Website and reviewing the commission applicable to you from time to time.</li>
            <li>Access to the features of the Services may depend upon the subscription plan you have subscribed to. The features, functionalities, and fees applicable for each Service or under each subscription may differ. You also agree that we reserve the right to enable and/or disable certain features for you.</li>
            <li>If the payment method you have chosen for making payments towards your subscription plan supports auto renewal, the payment of the subscription fees will be on a recurring basis, and you authorize us to collect the subscription fees for the next subscription term(s).</li>
            <li>The Services may be modified to comply with the applicable laws. As a result of this, you may be unable to access or use all or any part of the Services. We shall not be liable to you for such inability to use the Services pursuant to our compliance with the applicable laws.</li>
            <li>Paype may reject payment in case (a) necessary authorization has not been obtained by you; (b) any transaction deemed to be fraudulent; (c) the card issuing bank advises that the card number does not match any number on file; or (d) there is insufficient funds available therein.</li>
        </ol>
        <h5 className="py-3">V. ROLES AND OBLIGATIONS</h5>
        <ol>
            <li>You agree and authorize Paype to share your information and make your details available to its partner banks/institutions, its group companies, affiliates, vendors, service providers/facility providers and other third parties, in so far as required for providing Services.</li>
            <li>You agree and acknowledge that for undertaking any payment and/or financial transaction through the Website, Paype may undertake due diligence measures and seek information required for Know-Your-Customer (“KYC”) purposes which as a customer/merchant you are obliged to give in accordance with laws applicable.</li>
            <li>You agree and covenant that before the commencement of any Service(s) under these ToU, you shall provide the necessary documents to enable Paype to conduct the due diligence in respect of inter alia you and your business activities. Paype shall have the right to share the KYC documents and other related documents with the facility providers or governmental authorities as required under the laws applicable. You expressly consent Paype to rely on the KYC documents provided by you for providing services.</li>
            <li>You agree that Paype shall not be responsible for any delivery, after-sales service, payment, invoicing or collection, customer enquiries, and/or any other obligations or service. You shall indemnify Paype against any claim arising from such services or obligations and shall bear any and all expenses and/or costs relating thereto.</li>
            <li>You agree not to use the Website and/or Services for any purpose that is unlawful, illegal or forbidden by these ToU, or any applicable laws that might apply to you. We may, at our sole discretion, at any time and without advance notice or liability, suspend, terminate or restrict your access to all or any component of the Website and/or Services.</li>
            <li>You agree not to post or transmit to or through this Website (a) any unlawful, threatening, libellous, defamatory, obscene, pornographic or other material or content that would violate rights of publicity and/or privacy or that would violate any law or that harms minors in any way; (b) any commercial material or content; (c) any material or content infringes, misappropriates or violates any copyright, trademark, patent right or other proprietary right of any third party; (d) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; (e) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting to any other nation; (f) impersonates another person; or (g) is illegal in any other way. You shall be solely liable for any damages resulting from any violation of the foregoing restrictions, or any other harm resulting from your posting of content to this Website.</li>
            <li>You further covenant and agree that you shall ensure that: (a) Your use of the Services are solely for your own bona fide business activities which are in compliance with the applicable laws and also the instructions issued from time to time by the Paype and its facility providers; (b) you shall not resell or assign the Services, in whole or in part, or otherwise allow the use of the Services by any third parties or your affiliates; (c) your use of the Services does not facilitate any activity which is unlawful, illegal, unauthorised, is carried on with the intent to defraud, or is likely to result in your unjust enrichment and/or unlawful gain; or (d) you hold informed consent of your Customers to share customer’s information with Paype ad its affiliates in connection with the Services and/or for the purposes of sharing with governmental authorities as and when demanded under the applicable laws.</li>
            <li>You shall not use the Services in the manner (a) that infringe any proprietary rights, including but not limited to copyrights, patents, trademarks, or trade secrets; or (b) except as may be provided hereunder, copy, display, distribute, modify, publish, reproduce, store, transmit, post, translate, create any derivative works from, or license the Services.</li>
            <li>You agree that you shall permit and facilitate us, our officers, employees, agents, advisors, auditors and other professionals to (a) inspect and audit your records relating to Services provided on Website; (b) seek information relating to documents furnished by you; or (c) monitor your compliance with terms and conditions hereunder. In the event any information is false, Paype reserves the right to take action against you including but not limited to suspension of your Account.</li>
            <li>You agree that we reserve the right to observe, and/or track your activities on the Website and inform any such activity undertaken by you to any authority, which in our opinion is or is suspected to be fraudulent, unauthorised, illegal, and/or breaches ToU in any manner. Further, we reserve the right to charge a penalty fee you from you, for abusing our Website, towards the charges incurred for the investigation, operational handling, and legal consultation charges.</li>
            <li>You acknowledge that when you upload or post content on the Website, you grant us an irrevocable, perpetual, royalty-free, non-exclusive, and worldwide license to copy, display, transmit, review, reproduce, store and archive the content.</li>
            <li>You agree that you are not allowed to store payment data of the Customers, unless permitted under the applicable laws. Should you store any data in compliance with applicable laws, you agree to ensure all applicable standards in this regard are complied with.</li>
            <li>You agree that upon deletion of your Account, we reserve the right to retain such data of yours to the extent permitted under the applicable law.</li>
            <li>You are hereby restricted from transferring or attempting to transfer your financial liabilities to the Customers by employing any methods and/or undertakings any actions that amount to coercing the Customers to waive their dispute rights pertaining to transaction amounts.</li>
        </ol>
        <h5 className="py-3">VI. THIRD PARTY SERVICES</h5>
        <ol>
            <li>The Services may include services, content, documents and information owned by, licensed to, or otherwise made available by a third-party (“Third-Party Services”), and may also include links to Third-Party Services. You understand and acknowledge that the Third-Party Services are the responsibility of the third-party that created or provided it and acknowledge that use of such Third-Party Services is solely at your own risk.2</li>
            <li>You acknowledge and agree that Paype is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. You further acknowledge and agree that Paype shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods, or services available on or through any such site or resource.</li>
            <li>Your interaction with any third party accessed through the Website is at our own risk, and Paype will have no liability with respect to the acts, omissions, errors, representations, warranties, breaches or negligence of any such third parties for any personal injuries, death, property damage, or other damages or expenses resulting from your interactions with the third parties.</li>
        </ol>
        <h5 className="py-3">VII. DISCLAIMER</h5>
        <ol>
            <li>Paype warrants that the Service(s) shall be provided materially in accordance with the services documentation available on the Website. Paype warrants that the Service(s) will perform in all material respects in accordance with these ToU. To the maximum extent permitted by applicable laws and except as stated in these ToU, the Services are provided on an “as is” basis. You acknowledge that Paype does not warrant the Service(s) will be uninterrupted or error free or fit for your specific business purposes.</li>
            <li>Paype shall not be responsible for any losses sustained through (a) the use of counterfeit or stolen bank cards or stolen devices; (b) fraudulent electronic transactions; or (c) quality and service-related claims pertaining to the Services.</li>
        </ol>
        <h5 className="py-3">VIII.LIMITATION OF LIABILITY</h5>
        <p>Notwithstanding anything to the contrary contained herein, neither Paype nor any of its affiliates or related parties shall have any liability to you or any third party for any indirect, incidental, special or consequential damages or any loss of revenue or profits arising under, directly or indirectly, or relating, in any manner whatsoever, to these ToU, including any action taken by an authority or facility provider. You agree to waive, release, discharge, and hold harmless Paype and its affiliates, subsidiaries, and each of their directors, officers, employees, and agents, from any and all claims, losses, damages, liabilities, expenses and causes of action arising out of your use of the Website or the Services.</p>
        <h5 className="py-3">IX. INTELLECTUAL PROPERTY</h5>
        <ol>
            <li>All rights, title, and interest in and to the Website and Services, including all intellectual property rights arising out of the Website and the Services, are owned by or otherwise licensed to us. Subject to compliance with these ToU, we grant you a non-exclusive, non-transferrable, non-sub licensable, royalty-free, revocable, and limited license to use the Website in accordance with these ToU.</li>
            <li>We may request you to submit suggestions and other feedback, including bug reports and vulnerability disclosures, relating to the Services from time to time (“Feedback”). We may freely use, copy, disclose, publish, display, distribute, and exploit the Feedback we receive from you, without any payment of royalty, acknowledgement, prior consent, or any other form of restriction arising out of your intellectual property rights.</li>
            <li>Except as stated in these ToU, nothing in this ToU should be construed as conferring any right in or license to our or any third-party’s intellectual property rights.</li>
        </ol>
        <h5 className="py-3">X. INDEMNITY</h5>
        <ol>
            <li>You agree to indemnify and hold Paype and its affiliates, officers, directors, agents and employees harmless from and against any direct or indirect losses, actions, causes of action, demands, damages, penalties, cost and expenses, claim, fines, or other costs or expenses of any kind or nature, including reasonable attorneys’ fees arising from or relating to (a) acts, commissions or omissions, errors, misrepresentations, misconduct, negligence, fraud, forgery, dishonesty, violation attributable to you and/or your personnel, agents, representatives or any third party who may use your Account, your access to the Website, use of the Services, violation or infringement of this ToU; or (b) contravention of applicable law.</li>
            <li>This clause shall survive the termination of these ToU.</li>
        </ol>
        <h5 className="py-3">XI. TERM AND TERMINATION</h5>
        <ol>
            <li>This ToU shall remain in effect as long as you continue to access the Website, avail the Services, or maintain an Account on the Website.</li>
            <li>Notwithstanding other legal remedies that may be available to you, we may at our sole discretion, limit your access or activity (either temporarily or indefinitely), or suspend or terminate your Account or refuse to provide you with access to the Website and the Services, without providing you with notice or cause, for reason including but not limited to the breach of your obligations, covenants, representation under the ToU or failure to repay or fraudulent payment for transactions.</li>
        </ol>
        <h5 className="py-3">XII. GOVERNING LAWS AND JURISDICTION</h5>
        <p>These ToU shall be governed by and construed in accordance with the laws of India without reference to conflict of laws, principles and disputes arising in relation hereto shall be subject to the exclusive jurisdiction of courts, tribunals, forum or authorities at New Delhi. The place of jurisdiction shall be exclusively in New Delhi.</p>
        <h5 className="py-3">XIII. MISCELLANEOUS</h5>
        <ol>
            <li>If any provision of these ToU is deemed unlawful, invalid, or unenforceable by court or any other competent authority for any reason, then the other provisions will continue in full force and effect.</li>
            <li>The failure of Paype to enforce or to exercise any term of these ToU does not constitute a waiver of such term and shall in no way affect its rights to later to enforce or to exercise the term in question.</li>
            <li>Neither party shall be liable to the other in respect of anything which, apart from this provision, may constitute breach of this ToU arising by reason of Force Majeure, namely circumstances beyond the control of either party which shall include (but shall not be limited to) acts of God, Civil or military authority, acts of the public enemy, war, riots, civil disturbances, insurrections, accidents, explosions, fires, earthquakes, floods, transportation embargoes, epidemics, acts of government, its agencies or officers.</li>
            <li>None of the provisions of these ToU shall be deemed to constitute a partnership or agency between you and the Company and no party shall have any authority to bind the other in any way.</li>
            <li>Any complaints, abuse or concerns with regards to content, comment or breach of these ToU shall be immediately informed to the designated Grievance officer as mentioned below via in writing or through email signed with the electronic signature to Grievance Officer at disputes@Paypepl.com or write at the following address:                                                                                                                                                                                                                                                                                          Unit No. 402, 4th Floor, Tower B4, Spaze Itech Park, Sohna Road, Sector 49, Gurugram-122018</li>
            <li>The ToU, together with the ‘Privacy Policy’ and other guidelines and policies, shall constitute the entire agreement between you and us concerning the use of the Platform. No failure or delay by us in exercising any right, power or privilege under the ToU shall operate as a waiver of such right or acceptance of any variation of the ToU and nor shall any single or partial exercise by either party of any right, power or privilege preclude any further exercise of that right or the exercise of any other right, power or privilege.</li>
        </ol>
        <h5 className="py-3">XIV. GRIEVANCE OFFICER</h5>
        <p>In compliance with Information Technology Act, 2000 and the rules made thereunder, the Grievance Officer of Company for the purpose of these ToU shall be Nodal Officer with email address disputes@Paypepl.com. Company may change the aforesaid details from time to time under intimation to you.</p>
        <p>Our Grievance Officer will endeavour to resolve the issue within 24-48 hours of the receipt of the complaint</p>
      </div>
      <Footer />
    </div>
  );
}
